all: counter Knapsack

counter: counter.cpp FileParser.hh sortedArray.hh NickThread.hh Counter.hh 
	g++ counter.cpp -o counter -lpthread -g -std=gnu++0x 

Knapsack: Knapsack.cpp
	g++ Knapsack.cpp -o Knapsack -lpthread -g -std=gnu++0x 

