all: counter Knapsack Maze RedBlackTree

counter: counter.cpp FileParser.hh sortedArray.hh NickThread.hh Counter.hh 
	g++ counter.cpp -o counter -lpthread -g -std=gnu++0x 

Knapsack: Knapsack.cpp
	g++ Knapsack.cpp -o Knapsack -lpthread -g -std=gnu++0x 

Maze: Maze.cpp
	g++ Maze.cpp -o Maze -lpthread -g -std=gnu++0x 

RedBlackTree: RedBlackTree.cc
	g++ RedBlackTree.cc -o RedBlackTree -lpthread -g -std=gnu++0x 